apiVersion: v1
kind: Service
metadata:
  name: {{ include "gpc.fullname" . }}-fe
  labels:
    {{- include "gpc.labelsFrontEnd" . | nindent 4 }}
spec:
  type: {{ .Values.service.frontEnd.type }}
  ports:
    - port: {{ .Values.service.frontEnd.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gpc.selectorLabelsFrontEnd" . | nindent 4 }}
