export enum PassaggiStato {  
    'BozzaToInserita' = 'La pratica è stata acquisita e protocollata',
    'InseritaToVerificaFormale' = 'La pratica è stata assegnata/presa in carico per la relativa istruttoria',
    'InseritaToRichiestaLavori' = 'E\' stata richiesta l\'esecuzione di lavori per evitare la revoca',
    'VerificaFormaleToRichiestaPareri' = 'La pratica è stata verificata e sono stati richiesti i pareri agli Uffici di competenza',
    'VerificaFormaleToNecessariaIntegrazione' = 'La pratica è stata verificata ma è necessaria una integrazione da parte dell\'istante',
    'VerificaFormaleToPraticaDaRigettare' = 'La pratica è stata verificata ed è da rigettare',
    'VerificaFormaleToPraticaDaRevocare' = 'La pratica è stata verificata e la concessione è da revocare',
    'VerificaFormaleToPreavvisoDiniego' = 'La pratica è stata verificata ed è stato emesso il preavviso di diniego',
    'ApprovataToConcessioneValida' = 'La determina esecutiva è stata emessa e la concessione è valida',
    'VerificaFormaleToApprovata' = 'La pratica è stata verificata ed è stata approvata',
    'VerificaFormaleToAttesaFineLavori' = 'E\' stata verificata la documentazione e si attende la fine dei lavori da parte dell\'istante per evitare la revoca',
    'VerificaFormaleToVerificaFormaleDecadenza' = 'Alla pratica sono stati aggiunti i documenti relativi alla decadenza',
    'RichiestaPareriEsprimiParerePolizia' = 'La Polizia Locale ha effettuato i controlli di propria competenza',
    'RichiestaPareriEsprimiParereUTD' = 'L\'Ufficio Tecnico Decentrato ha effettuato i controlli di propria competenza',
    'RichiestaPareriEsprimiParereUrbanistica' = 'La Ripartizione Urbanistica ha effettuato i controlli di propria competenza',
    'RichiestaPareriToRichiestaPareri' = 'Sono stati richiesti ulteriori pareri agli Uffici di competenza',
    'RichiestaPareriToArchiviata' = 'La revoca è stata annullata e la pratica relativa è stata archiviata',
    'RichiestaPareriToApprovata' = 'La pratica è stata verificata ed è stata approvata',
    'RichiestaPareriToPraticaDaRigettare' = 'La pratica è stata verificata ed è da rigettare',
    'RichiestaPareriToPraticaDaRevocare' = 'I pareri sono stati rilasciati e la concessione è da revocare',
    'RichiestaPareriToPreavvisoDiniego' = 'La pratica è stata verificata ed è stato emesso il preavviso di diniego',
    'RichiestaPareriToNecessariaIntegrazione' = 'La pratica è stata verificata ma è necessaria una integrazione da parte dell\'istante',
    'AttesaDiPagamentoToProntoAlRilascio' = 'I tributi previsti sono stati pagati ed è possibile procedere al rilascio del segnale',
    'NotificaRettificaPratica' = 'E\' stata notificata la necessità di rettificare la concessione a causa di errori materiali',
    'RettificaPratica' = 'La concessione ha subito un processo di rettifica e la relativa determina è stata adottata',
    'AggiuntaTagRFID' = 'Il Tag RFID del segnale indicatore è stato associato alla pratica',
    'ConcessioneValidaToVerificaFormale' = 'E\' stata avviata la richiesta di proroga',
    'Regolarizzazione' = 'E\' stato avviato il processo di regolarizzazione della pratica',
    'ApprovataToAttesaDiPagamento' = 'La determina esecutiva è stata emessa e si è in attesa del pagamento dei tributi previsti',
    'ApprovataToProntoAllaRestituzione' = 'La determina esecutiva è stata emessa. E\' necessario procedere con la restituzione del segnale indicatore',
    'ProntoAlRilascioToConcessioneValida' = 'Il segnale indicatore è stato rilasciato e la concessione è valida',
    'ProntoAllaRestituzioneToArchiviata' = 'Il segnale indicatore è stato riconsegnato dall\'istante e la concessione è stata archiviata',
    'PraticaDaRigettareToRigettata' = 'La richiesta è stata rigettata e la relativa determina è stata emessa',
    'PraticaDaRevocareToProntoAllaRestituzione' = 'La determina esecutiva di revoca è stata emessa. E\' necessario procedere con la restituzione del segnale indicatore',
    'PraticaDaRigettareToApprovata' = 'La rinuncia è stata approvata con l\'utilizzo della cauzione infruttifera',
    'NecessariaIntegrazioneToVerificaFormale' = 'La pratica è stata integrata dall\'istante',
    'PreavvisoDiniegoToVerificaFormale' = 'La pratica è stata integrata dall\'istante in risposta al preavviso del diniego',
    'RichiestaLavoriToVerificaFormale' = 'L\'istante ha risposto relativamente all\'inizio dei lavori e la pratica può essere istruita',
    'AttesaFineLavoriToVerificaFormale' = 'L\'istante ha ultimato i lavori per evitare la revoca e l\'istruttoria può essere completata',
    'EsenzioneCUP' = 'Dichiarazione di esenzione dal pagamento del CUP'
}


// Stati del sistema {  
//     'Bozza' = 0,
//     'Inserita' = 1,
//     'Verifica formale' = 2,
//     'Richiesta pareri' = 3,
//     'Necessaria integrazione' = 4,
//     'Pratica da rigettare' = 5,
//     'Approvata' = 6,
//     'Preavviso diniego' = 7,
//     'Attesa di pagamento' = 8,
//     'Pronto al rilascio' = 9,
//     'Concessione valida' = 10,
//     'Pronto alla restituzione' = 11,
//     'Richiesta lavori' = 12,
//     'Attesa fine lavori' = 13,
//     'Pratica da revocare' = 14,
//     'Regolarizzazione' = 15,
//     'Archiviata'= 18,
//     'Revocata'= 19,
//     'Rigettata'= 20
// }