const StatoPraticaPassiCarrabiliEnum = {

    0: 'Bozza',
    1: 'Inserita',
    2: 'Verifica formale',
    3: 'Richiesta pareri',
    4: 'Necessaria integrazione',
    5: 'Pratica da rigettare',
    6: 'Approvata',
    7: 'Preavviso diniego',
    8: 'Attesa di pagamento',
    9: 'Pronto al rilascio',
    10: 'Concessione valida',
    11: 'Pronto alla restituzione',
    12: 'Richiesta lavori',
    13: 'Attesa fine lavori',
    14: 'Pratica da revocare',
    15: 'Regolarizzazione',
    // 16: '',
    // 17: '',
    18: 'Archiviata',
    19: 'Revocata',
    20: 'Rigettata',

    'Bozza': 0,
    'Inserita': 1,
    'Verifica formale': 2,
    'Richiesta pareri': 3,
    'Necessaria integrazione': 4,
    'Pratica da rigettare': 5,
    'Approvata': 6,
    'Preavviso diniego' : 7,
    'Attesa di pagamento': 8,
    'Pronto al rilascio': 9,
    'Concessione valida': 10,
    'Pronto alla restituzione': 11,
    'Richiesta lavori': 12,
    'Attesa fine lavori': 13,
    'Pratica da revocare': 14,
    'Regolarizzazione': 15,
    // '': 16,
    // '': 17,  
    'Archiviata': 18,
    'Revocata': 19,
    'Rigettata': 20
}

module.exports = { StatoPraticaPassiCarrabiliEnum };